services:
  ssh-relay:
    build: .
    container_name: "ssh-relay"
    environment:
      - REMOTE_USER
      - REMOTE_SERVER
      - REMOTE_PORT
      - TARGET_PORT
      - SSH_FILE_NAME
      - SERVER_ALIVE_INTERVAL
      - SERVER_ALIVE_COUNT
    volumes:
      # mount the ssh information to the docker image
      - ./ssh:/root/.ssh
    # default forward traffic to the host machine
    network_mode: host
    restart: unless-stopped